### ISSUE TITLE
Automatically update the calendar via Twitter

### ISSUE THREAD

**Issue by ItsASine** [DryTopSAND/SAND#14]
- [ ] Look into the Twitter api for usage
- [ ] Figure out Moon's standard phrasing for new event times
- [ ] Create a bot that can understand Moon and update the site

Note: this will be a huge undertaking, but has great long term gains so 🤷‍♀️

**Comment by gmriggs** [comment]
Hey ItsASine,

I can start writing some code for this feature if it would help.

Some initial thoughts and questions about the design:

- Are there any pros/cons to using the Twitter API vs. the GW2 API? My initial impression would be to read the messages from the guild MOTD, since the front page already has some code written for that.

- The message parser can operate independently of the source of the messages (regardless if they are read from Twitter or the guild MOTD) so it can be a separate piece and adjusted for any nuances in the wording of the messages.

- For the part that posts to the Google Calendar API, I'm assuming this should be written in JS?
 I am wondering where this bit of code should "live", ie. where it will be run from.

The code for the site currently appears to be mostly client-side and run in the visitors' browsers, but this seems more like a server-side feature that would do the updating from the proper account.

Anyway, let me know if I can help out with anything in particular!

**Comment by ItsASine** [comment]
@gmriggs 

I'm sorry I suck! Work and grad school eat up my time royally (I'm on PTO today because of traveling for a wedding... that's why I have time ;.;). 

1. To be fair, you'd know Moon's habits more than I would. If the MotD seems like the most consistent location for these updates, then that would be easier than wrangling her tweets. :+1:
2. Good plan :+1:
3. The site is pretty much purely JS, so that'd be ideal. Unless you know of more PHP or something that would make it easier to maintain. I was entertaining the notion of moving everything to Angular and Typescript later #15 
4. The site is "hosted" on GitHub Pages as to cut down on costs (with Moon being in school and whatnot, right now the only cost is the $15/yr I pay for the drytopsand.com name). So we don't even have a non-client side. Right now since everything's been a GET, I haven't really cared about API keys floating around. But you're right, a POST would need more nuance... I was just really hoping to avoid a $15/month server hosting bill.

**Comment by gmriggs** [comment]
Hey @ItsASine,

No worries! You mentioned that you have a lot of other responsibilities, so I understand if it takes some time to reply

Sounds good to me... I can start writing the parser and Google Calendar code in JS to maintain consistency with the rest of the codebase.

If you decide to start writing in Angular / TypeScript, I can certainly port these calendar features over to whichever language is best for the site.
