### ISSUE TITLE
Github DNS update

### ISSUE THREAD

**Issue by gmriggs** [DryTopSAND/SAND#21]
Hey @ItsASine,

When checking in recent updates to the SAND site, Github has been sending the following email:

```
The page build completed successfully, but returned the following warning for the `gh-pages` branch:

The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://help.github.com/en/articles/using-a-custom-domain-with-github-pages.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```

not sure who can update the github ip addresses drytopsand.com points to, but it sounds like they might need updated

https://help.github.com/en/articles/setting-up-an-apex-domain
https://help.github.com/en/articles/troubleshooting-custom-domains

```
If you're using an A record that points to 192.30.252.153 or 192.30.252.154, you'll need to update your DNS settings for your site to be available over HTTPS or served with a Content Delivery Network. For more information, see "HTTPS errors."
```

drytopsand.com is currently pointing to:

Name:   drytopsand.com
Address: 192.30.252.153
Name:   drytopsand.com
Address: 192.30.252.154

they recommend updating to these addresses:
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153

it sounds like the new addresses support https, the old ones should still work for now, just doesnt support https and caching

not sure if this will be a required DNS update in the future, but it sounds like they are recommending people using github pages update to these new addresses

(cc: @MuirelltheMoon )

**Comment by ItsASine** [comment]
- [x] - Actually address the old DNS issue

Old: 
![Screen Shot 2019-05-14 at 8 16 33 PM](https://user-images.githubusercontent.com/11020425/57740491-26ca5400-7686-11e9-8920-ef3ae89f3cfe.png)

New:
![Screen Shot 2019-05-14 at 8 23 13 PM](https://user-images.githubusercontent.com/11020425/57740495-2c279e80-7686-11e9-97a5-3cc54fa40b08.png)

- [x] Migrate to Google Domains to save $3/yr :P And make it easier to share if anyone else wants to muck around with this kind of devops stuff

In Progress:
![Screen Shot 2019-05-14 at 8 24 03 PM](https://user-images.githubusercontent.com/11020425/57740516-3ea1d800-7686-11e9-8e2c-ec91aedfc619.png)

- [x]   Move build process from Github Pages entirely to Netlify, so that it can give us autorenewing https certificates out of the box

**Comment by gmriggs** [comment]
awesome, tyvm!

**Comment by ItsASine** [comment]
@gmriggs 

This is done and we now have HTTPS 🎉 

The only thing I did that should make a difference to you and @MuirelltheMoon is that the default branch name is now `master` instead of `gh-pages`. If there's a branch named gh-pages, Github will _always_ deploy it as a Github Pages site, with no way of turning that off, even if the site is also built elsewhere. So moving to Netlify meant needing to rename that for less redundancy (why bother moving if we're going to have to keep updating Github Pages stuff anyway?)

**Comment by gmriggs** [comment]
yay https \o/
